<?php

define('REFUS_TYPE_PRODUIT__AJOUTER', 158);
define('REFUS_TYPE_PRODUIT__AJOUT_BLOQUEE', 159);
define('ERR_TYPE_PRODUIT__AJOUTER__AJOUT_REFUSE', 160);
define('ERR_TYPE_PRODUIT__AJOUTER_3__ECHEC_AJOUT', 161);
define('ERR_TYPE_PRODUIT__MODIFIER__CODE_TYPE_PRODUIT_INEXISTANT', 162);
define('REFUS_TYPE_PRODUIT__MODIFIER', 163);
define('REFUS_TYPE_PRODUIT__MODIFICATION_BLOQUEE', 164);
define('ERR_TYPE_PRODUIT__MODIFIER__AUCUN_CHANGEMENT', 165);
define('ERR_TYPE_PRODUIT__MODIFIER_3__AUCUN_CHANGEMENT', 166);
define('ERR_TYPE_PRODUIT__MODIFIER_4__AUCUN_CHANGEMENT', 167);
define('ERR_TYPE_PRODUIT__SUPPRIMER_2__CODE_TYPE_PRODUIT_INEXISTANT', 168);
define('REFUS_TYPE_PRODUIT__SUPPRIMER', 169);
define('REFUS_TYPE_PRODUIT__SUPPRESSION_BLOQUEE', 170);
define('ERR_TYPE_PRODUIT__SUPPRIMER__REFUSEE', 171);
define('ERR_TYPE_PRODUIT__SUPPRIMER_2__REFUSEE', 172);
define('ERR_TYPE_PRODUIT__SUPPRIMER_3__REFUSEE', 173);
