<?php

define('REFUS_PARAMETRE__AJOUTER', 174);
define('REFUS_PARAMETRE__AJOUT_BLOQUEE', 175);
define('ERR_PARAMETRE__AJOUTER__AJOUT_REFUSE', 176);
define('ERR_PARAMETRE__AJOUTER_3__ECHEC_AJOUT', 177);
define('ERR_PARAMETRE__MODIFIER__CODE_PARAMETRE_INEXISTANT', 178);
define('REFUS_PARAMETRE__MODIFIER', 179);
define('ACCES_CODE_PARAMETRE_REFUSE', 180);
define('REFUS_PARAMETRE__MODIFICATION_BLOQUEE', 181);
define('ERR_PARAMETRE__MODIFIER__AUCUN_CHANGEMENT', 182);
define('ERR_PARAMETRE__MODIFIER_3__AUCUN_CHANGEMENT', 183);
define('ERR_PARAMETRE__MODIFIER_4__AUCUN_CHANGEMENT', 184);
define('ERR_PARAMETRE__SUPPRIMER_2__CODE_PARAMETRE_INEXISTANT', 185);
define('REFUS_PARAMETRE__SUPPRIMER', 186);
define('REFUS_PARAMETRE__SUPPRESSION_BLOQUEE', 187);
define('ERR_PARAMETRE__SUPPRIMER__REFUSEE', 188);
define('ERR_PARAMETRE__SUPPRIMER_2__REFUSEE', 189);
define('ERR_PARAMETRE__SUPPRIMER_3__REFUSEE', 190);
