<?php

define('REFUS_UTILISATEUR__AJOUTER', 100);
define('REFUS_UTILISATEUR__AJOUT_BLOQUEE', 101);
define('ERR_UTILISATEUR__AJOUTER__UTILISATEUR_IDENTIFIANT_DOUBLON', 102);
define('ERR_UTILISATEUR__AJOUTER__UTILISATEUR_EMAIL_DOUBLON', 103);
define('ERR_UTILISATEUR__AJOUTER__AJOUT_REFUSE', 104);
define('ERR_UTILISATEUR__AJOUTER_3__ECHEC_AJOUT', 105);
define('ERR_UTILISATEUR__MODIFIER__CODE_UTILISATEUR_INEXISTANT', 106);
define('REFUS_UTILISATEUR__MODIFIER', 107);
define('ACCES_CODE_UTILISATEUR_REFUSE', 108);
define('REFUS_UTILISATEUR__MODIFICATION_BLOQUEE', 109);
define('ERR_UTILISATEUR__MODIFIER__AUCUN_CHANGEMENT', 110);
define('ERR_UTILISATEUR__MODIFIER_3__AUCUN_CHANGEMENT', 111);
define('ERR_UTILISATEUR__MODIFIER_4__AUCUN_CHANGEMENT', 112);
define('ERR_UTILISATEUR__SUPPRIMER_2__CODE_UTILISATEUR_INEXISTANT', 113);
define('REFUS_UTILISATEUR__SUPPRIMER', 114);
define('REFUS_UTILISATEUR__SUPPRESSION_BLOQUEE', 115);
define('ERR_UTILISATEUR__SUPPRIMER__REFUSEE', 116);
define('ERR_UTILISATEUR__SUPPRIMER_2__REFUSEE', 117);
define('ERR_UTILISATEUR__SUPPRIMER_3__REFUSEE', 118);
