<?php

define('REFUS_ARTICLE__AJOUTER', 119);
define('ERR_ARTICLE__AJOUTER__CODE_TYPE_PRODUIT_INEXISTANT', 120);
define('ACCES_CODE_TYPE_PRODUIT_REFUSE', 121);
define('REFUS_ARTICLE__AJOUT_BLOQUEE', 122);
define('ERR_ARTICLE__AJOUTER__AJOUT_REFUSE', 123);
define('ERR_ARTICLE__AJOUTER_3__ECHEC_AJOUT', 124);
define('ERR_ARTICLE__MODIFIER__CODE_ARTICLE_INEXISTANT', 125);
define('REFUS_ARTICLE__MODIFIER', 126);
define('ERR_ARTICLE__MODIFIER__CODE_TYPE_PRODUIT_INEXISTANT', 127);
define('ACCES_CODE_ARTICLE_REFUSE', 128);
define('REFUS_ARTICLE__MODIFICATION_BLOQUEE', 129);
define('ERR_ARTICLE__MODIFIER__AUCUN_CHANGEMENT', 130);
define('ERR_ARTICLE__MODIFIER_3__AUCUN_CHANGEMENT', 131);
define('ERR_ARTICLE__MODIFIER_4__AUCUN_CHANGEMENT', 132);
define('ERR_ARTICLE__SUPPRIMER_2__CODE_ARTICLE_INEXISTANT', 133);
define('REFUS_ARTICLE__SUPPRIMER', 134);
define('REFUS_ARTICLE__SUPPRESSION_BLOQUEE', 135);
define('ERR_ARTICLE__SUPPRIMER__REFUSEE', 136);
define('ERR_ARTICLE__SUPPRIMER_2__REFUSEE', 137);
define('ERR_ARTICLE__SUPPRIMER_3__REFUSEE', 138);
