<?php

define('REFUS_A_ARTICLE_COMMANDE__AJOUTER', 208);
define('ERR_A_ARTICLE_COMMANDE__AJOUTER__CODE_COMMANDE_INEXISTANT', 209);
define('ERR_A_ARTICLE_COMMANDE__AJOUTER__CODE_ARTICLE_INEXISTANT', 210);
define('ERR_A_ARTICLE_COMMANDE__AJOUTER__DOUBLON', 211);
define('REFUS_A_ARTICLE_COMMANDE__AJOUT_BLOQUEE', 212);
define('ERR_A_ARTICLE_COMMANDE__AJOUTER__REFUSE', 213);
define('ERR_A_ARTICLE_COMMANDE__AJOUTER_3__ECHEC_AJOUT', 214);
define('REFUS_A_ARTICLE_COMMANDE__SUPPRIMER', 215);
define('REFUS_A_ARTICLE_COMMANDE__SUPPRESSION_BLOQUEE', 216);
define('ERR_A_ARTICLE_COMMANDE__SUPPRIMER__REFUSE', 217);
define('ERR_A_ARTICLE_COMMANDE__SUPPRIMER_2__REFUSE', 218);
