<?php

define('REFUS_FILTRE__AJOUTER', 191);
define('REFUS_FILTRE__AJOUT_BLOQUEE', 192);
define('ERR_FILTRE__AJOUTER__AJOUT_REFUSE', 193);
define('ERR_FILTRE__AJOUTER_3__ECHEC_AJOUT', 194);
define('ERR_FILTRE__MODIFIER__CODE_FILTRE_INEXISTANT', 195);
define('REFUS_FILTRE__MODIFIER', 196);
define('ACCES_CODE_FILTRE_REFUSE', 197);
define('REFUS_FILTRE__MODIFICATION_BLOQUEE', 198);
define('ERR_FILTRE__MODIFIER__AUCUN_CHANGEMENT', 199);
define('ERR_FILTRE__MODIFIER_3__AUCUN_CHANGEMENT', 200);
define('ERR_FILTRE__MODIFIER_4__AUCUN_CHANGEMENT', 201);
define('ERR_FILTRE__SUPPRIMER_2__CODE_FILTRE_INEXISTANT', 202);
define('REFUS_FILTRE__SUPPRIMER', 203);
define('REFUS_FILTRE__SUPPRESSION_BLOQUEE', 204);
define('ERR_FILTRE__SUPPRIMER__REFUSEE', 205);
define('ERR_FILTRE__SUPPRIMER_2__REFUSEE', 206);
define('ERR_FILTRE__SUPPRIMER_3__REFUSEE', 207);
