<?php

define('REFUS_COMMANDE__AJOUTER', 139);
define('ERR_COMMANDE__AJOUTER__CODE_UTILISATEUR_INEXISTANT', 140);
define('REFUS_COMMANDE__AJOUT_BLOQUEE', 141);
define('ERR_COMMANDE__AJOUTER__AJOUT_REFUSE', 142);
define('ERR_COMMANDE__AJOUTER_3__ECHEC_AJOUT', 143);
define('ERR_COMMANDE__MODIFIER__CODE_COMMANDE_INEXISTANT', 144);
define('REFUS_COMMANDE__MODIFIER', 145);
define('ERR_COMMANDE__MODIFIER__CODE_UTILISATEUR_INEXISTANT', 146);
define('ACCES_CODE_COMMANDE_REFUSE', 147);
define('REFUS_COMMANDE__MODIFICATION_BLOQUEE', 148);
define('ERR_COMMANDE__MODIFIER__AUCUN_CHANGEMENT', 149);
define('ERR_COMMANDE__MODIFIER_3__AUCUN_CHANGEMENT', 150);
define('ERR_COMMANDE__MODIFIER_4__AUCUN_CHANGEMENT', 151);
define('ERR_COMMANDE__SUPPRIMER_2__CODE_COMMANDE_INEXISTANT', 152);
define('REFUS_COMMANDE__SUPPRIMER', 153);
define('REFUS_COMMANDE__SUPPRESSION_BLOQUEE', 154);
define('ERR_COMMANDE__SUPPRIMER__REFUSEE', 155);
define('ERR_COMMANDE__SUPPRIMER_2__REFUSEE', 156);
define('ERR_COMMANDE__SUPPRIMER_3__REFUSEE', 157);
