<?php

define('REFUS_A_FILTRE_PRODUIT__AJOUTER', 219);
define('ERR_A_FILTRE_PRODUIT__AJOUTER__CODE_FILTRE_INEXISTANT', 220);
define('ERR_A_FILTRE_PRODUIT__AJOUTER__CODE_ARTICLE_INEXISTANT', 221);
define('ERR_A_FILTRE_PRODUIT__AJOUTER__DOUBLON', 222);
define('REFUS_A_FILTRE_PRODUIT__AJOUT_BLOQUEE', 223);
define('ERR_A_FILTRE_PRODUIT__AJOUTER__REFUSE', 224);
define('ERR_A_FILTRE_PRODUIT__AJOUTER_3__ECHEC_AJOUT', 225);
define('REFUS_A_FILTRE_PRODUIT__MODIFIER', 226);
define('ERR_A_FILTRE_PRODUIT__MODIFIER__CODE_FILTRE_INEXISTANT', 227);
define('ERR_A_FILTRE_PRODUIT__MODIFIER__CODE_ARTICLE_INEXISTANT', 228);
define('ERR_A_FILTRE_PRODUIT__MODIFIER__INEXISTANT', 229);
define('REFUS_A_FILTRE_PRODUIT__MODIFICATION_BLOQUEE', 230);
define('ERR_A_FILTRE_PRODUIT__MODIFIER__AUCUN_CHANGEMENT', 231);
define('ERR_A_FILTRE_PRODUIT__MODIFIER_3__AUCUN_CHANGEMENT', 232);
define('ERR_A_FILTRE_PRODUIT__MODIFIER_4__AUCUN_CHANGEMENT', 233);
define('REFUS_A_FILTRE_PRODUIT__SUPPRIMER', 234);
define('REFUS_A_FILTRE_PRODUIT__SUPPRESSION_BLOQUEE', 235);
define('ERR_A_FILTRE_PRODUIT__SUPPRIMER__REFUSE', 236);
define('ERR_A_FILTRE_PRODUIT__SUPPRIMER_2__REFUSE', 237);
