<?php

define('REFUS_A_PARAMETRE_UTILISATEUR__AJOUTER', 238);
define('ERR_A_PARAMETRE_UTILISATEUR__AJOUTER__CODE_UTILISATEUR_INEXISTANT', 239);
define('ERR_A_PARAMETRE_UTILISATEUR__AJOUTER__CODE_PARAMETRE_INEXISTANT', 240);
define('ERR_A_PARAMETRE_UTILISATEUR__AJOUTER__DOUBLON', 241);
define('REFUS_A_PARAMETRE_UTILISATEUR__AJOUT_BLOQUEE', 242);
define('ERR_A_PARAMETRE_UTILISATEUR__AJOUTER__REFUSE', 243);
define('ERR_A_PARAMETRE_UTILISATEUR__AJOUTER_3__ECHEC_AJOUT', 244);
define('REFUS_A_PARAMETRE_UTILISATEUR__MODIFIER', 245);
define('ERR_A_PARAMETRE_UTILISATEUR__MODIFIER__CODE_UTILISATEUR_INEXISTANT', 246);
define('ERR_A_PARAMETRE_UTILISATEUR__MODIFIER__CODE_PARAMETRE_INEXISTANT', 247);
define('ERR_A_PARAMETRE_UTILISATEUR__MODIFIER__INEXISTANT', 248);
define('REFUS_A_PARAMETRE_UTILISATEUR__MODIFICATION_BLOQUEE', 249);
define('ERR_A_PARAMETRE_UTILISATEUR__MODIFIER__AUCUN_CHANGEMENT', 250);
define('ERR_A_PARAMETRE_UTILISATEUR__MODIFIER_3__AUCUN_CHANGEMENT', 251);
define('ERR_A_PARAMETRE_UTILISATEUR__MODIFIER_4__AUCUN_CHANGEMENT', 252);
define('REFUS_A_PARAMETRE_UTILISATEUR__SUPPRIMER', 253);
define('REFUS_A_PARAMETRE_UTILISATEUR__SUPPRESSION_BLOQUEE', 254);
define('ERR_A_PARAMETRE_UTILISATEUR__SUPPRIMER__REFUSE', 255);
define('ERR_A_PARAMETRE_UTILISATEUR__SUPPRIMER_2__REFUSE', 256);
