<?php declare(strict_types=1);

define('REFUS_A_FILTRER__AJOUTER', 297);
define('ERR_A_FILTRER__AJOUTER__CODE_UTILISATEUR_INEXISTANT', 298);
define('ERR_A_FILTRER__AJOUTER__CODE_VUE_UTILISATEUR_INEXISTANT', 299);
define('ERR_A_FILTRER__AJOUTER__DOUBLON', 300);
define('REFUS_A_FILTRER__AJOUT_BLOQUEE', 301);
define('ERR_A_FILTRER__AJOUTER__REFUSE', 302);
define('ERR_A_FILTRER__AJOUTER_3__ECHEC_AJOUT', 303);
define('REFUS_A_FILTRER__SUPPRIMER', 304);
define('REFUS_A_FILTRER__SUPPRESSION_BLOQUEE', 305);
define('ERR_A_FILTRER__SUPPRIMER__REFUSE', 306);
define('ERR_A_FILTRER__SUPPRIMER_2__REFUSE', 307);
