<?php
include __DIR__ . '/erreurs/erreurs__utilisateur.php';
include __DIR__ . '/langues/fr/utilisateur.php';
include __DIR__ . '/erreurs/erreurs__article.php';
include __DIR__ . '/langues/fr/article.php';
include __DIR__ . '/erreurs/erreurs__commande.php';
include __DIR__ . '/langues/fr/commande.php';
include __DIR__ . '/erreurs/erreurs__type_produit.php';
include __DIR__ . '/langues/fr/type_produit.php';
include __DIR__ . '/erreurs/erreurs__parametre.php';
include __DIR__ . '/langues/fr/parametre.php';
include __DIR__ . '/erreurs/erreurs__filtre.php';
include __DIR__ . '/langues/fr/filtre.php';
include __DIR__ . '/erreurs/erreurs__a_article_commande.php';
include __DIR__ . '/langues/fr/a_article_commande.php';
include __DIR__ . '/erreurs/erreurs__a_filtre_produit.php';
include __DIR__ . '/langues/fr/a_filtre_produit.php';
include __DIR__ . '/erreurs/erreurs__a_parametre_utilisateur.php';
include __DIR__ . '/langues/fr/a_parametre_utilisateur.php';
