<?php declare(strict_types=1);

// utilisateur_Civilite_Type
define('UTILISATEUR_CIVILITE_TYPE_ETAT_1', 1);
define('UTILISATEUR_CIVILITE_TYPE_ETAT_2', 2);
define('UTILISATEUR_CIVILITE_TYPE_ETAT_3', 3);

// article_Saison_Type
define('ARTICLE_SAISON_TYPE_ETAT_1', 1);
define('ARTICLE_SAISON_TYPE_ETAT_2', 2);
define('ARTICLE_SAISON_TYPE_ETAT_3', 3);

// article_Taille_Pays_Type
define('ARTICLE_TAILLE_PAYS_TYPE_ETAT_1', 1);
define('ARTICLE_TAILLE_PAYS_TYPE_ETAT_2', 2);
define('ARTICLE_TAILLE_PAYS_TYPE_ETAT_3', 3);

// vue_utilisateur_Filtre_Saison_Type
define('VUE_UTILISATEUR_FILTRE_SAISON_TYPE_ETAT_1', 1);
define('VUE_UTILISATEUR_FILTRE_SAISON_TYPE_ETAT_2', 2);
define('VUE_UTILISATEUR_FILTRE_SAISON_TYPE_ETAT_3', 3);

// vue_utilisateur_Filtre_Taille_Pays_Type
define('VUE_UTILISATEUR_FILTRE_TAILLE_PAYS_TYPE_ETAT_1', 1);
define('VUE_UTILISATEUR_FILTRE_TAILLE_PAYS_TYPE_ETAT_2', 2);
define('VUE_UTILISATEUR_FILTRE_TAILLE_PAYS_TYPE_ETAT_3', 3);
