<?php

define('API_REST_ACCESS_GET_A_FILTRE_PRODUIT', 'none');
define('API_REST_ACCESS_POST_A_FILTRE_PRODUIT', 'none');
define('API_REST_ACCESS_PUT_A_FILTRE_PRODUIT', 'none');
define('API_REST_ACCESS_DELETE_A_FILTRE_PRODUIT', 'none');
define('API_REST_ACCESS_OPTIONS_A_FILTRE_PRODUIT', 'all');
