<?php declare(strict_types=1);

define('API_REST_ACCESS_GET_A_PARAMETRE_UTILISATEUR', 'none');
define('API_REST_ACCESS_POST_A_PARAMETRE_UTILISATEUR', 'none');
define('API_REST_ACCESS_PUT_A_PARAMETRE_UTILISATEUR', 'none');
define('API_REST_ACCESS_DELETE_A_PARAMETRE_UTILISATEUR', 'none');
define('API_REST_ACCESS_OPTIONS_A_PARAMETRE_UTILISATEUR', 'all');
