<?php

define('API_REST_ACCESS_GET_COMMANDE', 'none');
define('API_REST_ACCESS_POST_COMMANDE', 'none');
define('API_REST_ACCESS_PUT_COMMANDE', 'none');
define('API_REST_ACCESS_DELETE_COMMANDE', 'none');
define('API_REST_ACCESS_OPTIONS_COMMANDE', 'all');
