<?php declare(strict_types=1);

define('API_REST_ACCESS_GET_SOUS_CATEGORIE_ARTICLE', 'none');
define('API_REST_ACCESS_POST_SOUS_CATEGORIE_ARTICLE', 'none');
define('API_REST_ACCESS_PUT_SOUS_CATEGORIE_ARTICLE', 'none');
define('API_REST_ACCESS_DELETE_SOUS_CATEGORIE_ARTICLE', 'none');
define('API_REST_ACCESS_OPTIONS_SOUS_CATEGORIE_ARTICLE', 'all');
