<?php

define('API_REST_ACCESS_GET_TYPE_PRODUIT', 'none');
define('API_REST_ACCESS_POST_TYPE_PRODUIT', 'none');
define('API_REST_ACCESS_PUT_TYPE_PRODUIT', 'none');
define('API_REST_ACCESS_DELETE_TYPE_PRODUIT', 'none');
define('API_REST_ACCESS_OPTIONS_TYPE_PRODUIT', 'all');
