<?php

define('API_REST_ACCESS_GET_UTILISATEUR', 'none');
define('API_REST_ACCESS_POST_UTILISATEUR', 'none');
define('API_REST_ACCESS_PUT_UTILISATEUR', 'none');
define('API_REST_ACCESS_DELETE_UTILISATEUR', 'none');
define('API_REST_ACCESS_OPTIONS_UTILISATEUR', 'all');
