<?php declare(strict_types=1);

$mf_dictionnaire_db['Code_utilisateur'] = ['type' => 'INT', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Identifiant'] = ['type' => 'VARCHAR', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Password'] = ['type' => 'PASSWORD', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Email'] = ['type' => 'VARCHAR', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Civilite_Type'] = ['type' => 'INT', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Prenom'] = ['type' => 'VARCHAR', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Nom'] = ['type' => 'VARCHAR', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Adresse_1'] = ['type' => 'VARCHAR', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Adresse_2'] = ['type' => 'VARCHAR', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Ville'] = ['type' => 'VARCHAR', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Code_postal'] = ['type' => 'VARCHAR', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Date_naissance'] = ['type' => 'DATE', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Accepte_mail_publicitaire'] = ['type' => 'BOOL', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Administrateur'] = ['type' => 'BOOL', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['utilisateur_Fournisseur'] = ['type' => 'BOOL', 'entite' => 'utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['Code_article'] = ['type' => 'INT', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Libelle'] = ['type' => 'VARCHAR', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Description'] = ['type' => 'TEXT', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Saison_Type'] = ['type' => 'INT', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Nom_fournisseur'] = ['type' => 'VARCHAR', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Url'] = ['type' => 'VARCHAR', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Reference'] = ['type' => 'VARCHAR', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Couleur'] = ['type' => 'VARCHAR', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Code_couleur_svg'] = ['type' => 'VARCHAR', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Taille_Pays_Type'] = ['type' => 'INT', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Taille'] = ['type' => 'INT', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Matiere'] = ['type' => 'VARCHAR', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Photo_Fichier'] = ['type' => 'VARCHAR', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Prix'] = ['type' => 'FLOAT', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['article_Actif'] = ['type' => 'BOOL', 'entite' => 'article', 'src' => 'db'];
$mf_dictionnaire_db['Code_commande'] = ['type' => 'INT', 'entite' => 'commande', 'src' => 'db'];
$mf_dictionnaire_db['commande_Prix_total'] = ['type' => 'FLOAT', 'entite' => 'commande', 'src' => 'db'];
$mf_dictionnaire_db['commande_Date_livraison'] = ['type' => 'DATE', 'entite' => 'commande', 'src' => 'db'];
$mf_dictionnaire_db['commande_Date_creation'] = ['type' => 'DATE', 'entite' => 'commande', 'src' => 'db'];
$mf_dictionnaire_db['Code_categorie_article'] = ['type' => 'INT', 'entite' => 'categorie_article', 'src' => 'db'];
$mf_dictionnaire_db['categorie_article_Libelle'] = ['type' => 'VARCHAR', 'entite' => 'categorie_article', 'src' => 'db'];
$mf_dictionnaire_db['Code_parametre'] = ['type' => 'INT', 'entite' => 'parametre', 'src' => 'db'];
$mf_dictionnaire_db['parametre_Libelle'] = ['type' => 'VARCHAR', 'entite' => 'parametre', 'src' => 'db'];
$mf_dictionnaire_db['Code_vue_utilisateur'] = ['type' => 'INT', 'entite' => 'vue_utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['vue_utilisateur_Recherche'] = ['type' => 'VARCHAR', 'entite' => 'vue_utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['vue_utilisateur_Filtre_Saison_Type'] = ['type' => 'INT', 'entite' => 'vue_utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['vue_utilisateur_Filtre_Couleur'] = ['type' => 'VARCHAR', 'entite' => 'vue_utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['vue_utilisateur_Filtre_Taille_Pays_Type'] = ['type' => 'INT', 'entite' => 'vue_utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['vue_utilisateur_Filtre_Taille_Max'] = ['type' => 'INT', 'entite' => 'vue_utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['vue_utilisateur_Filtre_Taille_Min'] = ['type' => 'INT', 'entite' => 'vue_utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['Code_sous_categorie_article'] = ['type' => 'INT', 'entite' => 'sous_categorie_article', 'src' => 'db'];
$mf_dictionnaire_db['sous_categorie_article_Libelle'] = ['type' => 'VARCHAR', 'entite' => 'sous_categorie_article', 'src' => 'db'];
$mf_dictionnaire_db['Code_conseil'] = ['type' => 'INT', 'entite' => 'conseil', 'src' => 'db'];
$mf_dictionnaire_db['conseil_Libelle'] = ['type' => 'VARCHAR', 'entite' => 'conseil', 'src' => 'db'];
$mf_dictionnaire_db['conseil_Description'] = ['type' => 'TEXT', 'entite' => 'conseil', 'src' => 'db'];
$mf_dictionnaire_db['conseil_Actif'] = ['type' => 'BOOL', 'entite' => 'conseil', 'src' => 'db'];
$mf_dictionnaire_db['a_commande_article_Quantite'] = ['type' => 'INT', 'entite' => 'a_commande_article', 'src' => 'db'];
$mf_dictionnaire_db['a_commande_article_Prix_ligne'] = ['type' => 'FLOAT', 'entite' => 'a_commande_article', 'src' => 'db'];
$mf_dictionnaire_db['a_parametre_utilisateur_Valeur'] = ['type' => 'INT', 'entite' => 'a_parametre_utilisateur', 'src' => 'db'];
$mf_dictionnaire_db['a_parametre_utilisateur_Actif'] = ['type' => 'INT', 'entite' => 'a_parametre_utilisateur', 'src' => 'db'];

$mf_dependances['sous_categorie_article'][]='article';
$mf_dependances['utilisateur'][]='commande';
$mf_dependances['categorie_article'][]='sous_categorie_article';
$mf_dependances['commande'][]='a_commande_article';
$mf_dependances['article'][]='a_commande_article';
$mf_dependances['utilisateur'][]='a_parametre_utilisateur';
$mf_dependances['parametre'][]='a_parametre_utilisateur';
$mf_dependances['utilisateur'][]='a_filtrer';
$mf_dependances['vue_utilisateur'][]='a_filtrer';

$mf_type_table_enfant['utilisateur']='entite';
$mf_type_table_enfant['article']='entite';
$mf_type_table_enfant['commande']='entite';
$mf_type_table_enfant['categorie_article']='entite';
$mf_type_table_enfant['parametre']='entite';
$mf_type_table_enfant['vue_utilisateur']='entite';
$mf_type_table_enfant['sous_categorie_article']='entite';
$mf_type_table_enfant['conseil']='entite';
$mf_type_table_enfant['a_commande_article']='association';
$mf_type_table_enfant['a_parametre_utilisateur']='association';
$mf_type_table_enfant['a_filtrer']='association';
